### ISSUE TITLE
Configuration Manager

### ISSUE THREAD

**Issue by rich492** [tormec/AcMenu#19]
Installed AcMenu via DokuWiki Extension Manager. The plugin seems to be working (shows in sidebar) but there is no entry in the Configuration Manager. Is it supposed be be this way, which would be unlike other plugins?

**Comment by tormec** [comment]
> [...] there is no entry in the Configuration Manager. Is it supposed be be this way, which would be unlike other plugins?

The plugin doesn't appear in the Configuration Manager because it doesn't require any user configuration to work.
At the moment the plugin can be configured using the settings provided by DokuWiki itself (like ACL, sneaky_index, hidepages) without reinventing its functionalities.

Pros: the code is much easier to maintain in case of bugs or a new DokuWiki version.
Cons: the plugin doesn't offer a rich variety of customization of the way the menu is rendered.

At the moment, I would like to follow this approach as much as possible because the idea is to offer an easy way to create even big menus but redirecting users to other plugins in case of more demanding requests.
