### ISSUE TITLE
Add support for H1 title replacement

### ISSUE THREAD

**Issue by jonathanwgebb** [tormec/AcMenu#21]
I am absolutely interested and impressed in your plugin. Only thing I would love to see is the ability for the names in the list to be replaced with H1 titles of the page. Other plugins such as nspages do this, but their plugins are not worth using in the sidebar. Your plugin works great in the sidebar and I would love to have the H1 support. Not sure if that is something you are wanting to look into, but I would be very interested if you could implement it

**Comment by tormec** [comment]
If the option [useheading](https://www.dokuwiki.org/config:useheading) is enabled, the plugin will use the first heading of each page instead of the name of the file. This behavior is described in the documentation of the plugin.

It's not possible - and I'm not interested in implementing - the use of the first heading only for some namespace.
